package main

import "fmt"

/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

solution = 4613732
*/
func main() {

	fib1 := 1
	fib2 := 2

	sum := 2

	for fib2 < 4000000 {
		nextFib := fib1 + fib2

		if nextFib%2 == 0 {
			sum += nextFib
		}
		
		fib1 = fib2;
		fib2 = nextFib;
	}
	fmt.Println(sum);
}
